name: Sync Fork and Redeploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    name: Sync fork with upstream and redeploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/dreamhartley/gemini-proxy-panel.git
          git fetch upstream
      
      - name: Sync fork with upstream
        run: |
          git checkout main
          git merge upstream/main
          git push origin main